### ISSUE TITLE
In built feature to mark blocked IPs/ranges as "ACC ignore"

### ISSUE THREAD

**Issue by Callanecc** [enwikipedia-acc/waca#178]
This isn't urgent or really important, but I think it would be useful to have a feature where CUs can mark IPs/ranges which are blocked as 'ACC ignore' within the tool for a few reasons:
1. It doesn't clog up the block log with information that most people won't understand
2. It doesn't mean changing blocks (and hence confusion as to who the blocking admin is)
3. One of the things I consider is whether the intended block target has the knowledge to check the block log and so request an account because they know it will be created for them.

The feature wouldn't need to detect if IPs/ranges were still blocked, it could be set similar to how ban management works, we set "ACC ignore" for x period of time or copy and paste in the block expiry. Then a message appears on the request page somewhere to note the ACC ignore.

Callanecc

**Comment by dqwiki** [comment]
This would be a major feature (in terms of code to write) request.

If we do go ahead with it, I would prefer to see a bigger plan before someone puts the work into it as not only are there privacy implications potentially from this, but it will be required to have a log of it's own, and track if the block is currently active.

**Comment by FastLizard4** [comment]
I am inclined to oppose/WONTFIX this.  Making this tracked on ACC instead of Wikipedia means that other admins/CUs who don't use ACC can't mark blocks as ACC ignore (should they know and/or desire to).

I also think implementing this would be a lot of effort for what I personally consider a marginal/superficial benefit, as well as assuming more PRIVPOL liability than we need.

**Comment by stwalkerster** [comment]
What actually would be the privpol concerns with this? Afaict this is a simple list of addresses/ranges, data which is unattached to specific requests, and is currently publicly visible data on enwiki?

Yes, it means some CUs who don't ever use ACC won't be able to log it themselves, but I think it's also unlikely that they'd mark it as ACC ignore currently.

It's a bit of effort, but not massively major. All the fiddly bits (range checks, CRUD ops, logging) are mainly already there and just need to be tied together.

**Comment by Callanecc** [comment]
The only admins who I've seen marking blocks as ACC ignore are DQ and I.
Really you don't want CUs who don't use ACC marking ranges as ACC ignore
because they don't know whether we're finding what we're looking for, or
perhaps what it means in detail. Also for most ranges the ACC ignore comes
after the block is made and the target UAs aren't as clear, the main
exception being where a range is too busy to start with, which needs a CU
to tell you and it's unlikely that such a massive block would be a CU
block, so you'd only know it was too bust once it was checked at ACC.

I can't think of a privacy policy issue related to this, especially given
that we already keep a list of banned IPs and email addresses for an
indefinite period of time.

Callanecc

**Comment by FastLizard4** [comment]
> I can't think of a privacy policy issue related to this, especially given that we already keep a list of banned IPs and email addresses for an indefinite period of time.

This could well be a privpol violation in itself, but there's no easy way around it.  The Foundation is very asinine about these things.

**Comment by Callanecc** [comment]
The difference being that the blocked IPs and email addresses is completely
generated but us, but blocked ranges are publicly available.

Callanecc

**Comment by FastLizard4** [comment]
Now, all this being said, my main issue is I personally don't think it's worth the effort, because I don't personally see the issue with just keeping things the way they are now.  But, if someone wants to contribute this (maybe submit a pull request, Callanecc?) I'd be happy to review and merge it.

**Comment by cyberpower678** [comment]
I share concerns on both ends, so here is a rather far fetched compromise.  What about a mini extension for the MW software that allows sysops to add a hidden flag only retrievable though the API.  The hidden flag would be the ACC ignore flag, that is set by checking a box along with the other options.  Then all the ACC interface would have to do is  do a simple API request to see if the ACC ignore flag is set.

Gesendet von Maximilian's iPhone. 
(Sent from Maximilian's iPhone.)

**Comment by FastLizard4** [comment]
If there's one thing that takes more process than dealing with privpol violations, it's getting WMF devops to deploy a new extension.  :P

**Comment by cyberpower678** [comment]
How true. :p

Gesendet von Maximilian's iPhone. 
(Sent from Maximilian's iPhone.)

**Comment by dqwiki** [comment]
The original issue I mentioned for privacy is the data retention. Because these would have to be attached to individual blocks (I wouldn't endorse it indefinitely for a full range), especially if there are two different sizes blocked (which i've done before). The MW mini-extension is too much for very little result at this point. It's not broken currently (and I prefer the onwiki log of it for certain reasons), why fix it?

**Comment by FastLizard4** [comment]
I think DQ hits the nail on the head pretty well here.  To put it another way, this seems like a solution in search of a problem.

I think that, if we were to implement this, it would be **necessary** to have a way for the tool to, via the MediaWiki API, pull a list of blocks and "attach" the ACC ignorable flag to an existing block on Wikipedia; this tag would then be removed on the tool automatically if the block is modified, expired, or removed on Wikipedia.

This is not trivial to implement, nor would a MW extension be easy to implement or even *feasible* due to WMF Ops' fairly strict requirements for extensions.  I'm closing this particular issue as WONTFIX for now, but if an intrepid volunteer wants to code this into the tool, I would welcome and happily review a pull request for it.
