### ISSUE TITLE
i18n

### ISSUE THREAD

**Issue by Matthewrbowker** [enwikipedia-acc/waca#234]
Proposal: Internationalize the ACC interface.  Thoughts?

**Comment by cyberpower678** [comment]
Unnecessary.  We serve the English Wikipedia and we users need to know proper English to even be allowed to join the team.  This is needless work.

**Comment by stwalkerster** [comment]
@Matthewrbowker internal, external, or both?

**Comment by Matthewrbowker** [comment]
@stwalkerster I am thinking more extrernal.  Both may be down the road, but I see no need for it now.

Especially with the SUL finalization, we have potential to handle account requests beyond the English Wikipedia.

**Comment by stwalkerster** [comment]
Yep, I agree there's no need for the internal interface.

External feels like a good idea at first glance, but you've got to think about several things:
* Effort involved (extracting to a messages table isn't too hard, but there'll have to be an internal management interface there too)
* Translation of page
* Will users then be expected to respond in the relevant language? If so, how does oversight work?
* What about updates to the text of the page for rules changes etc? Translating those as well will only add to the workload.

**Comment by Matthewrbowker** [comment]
@stwalkerster which is why I'm proposing rather than just doing.

translatewiki.net can handle most of the translation proper from what I understand.  And wrapping the messages in a data structure wouldn't be that hard, we would either put the translations in a separate repo or as a part of the main ACC repo and just pull them occasionally.  The difficult part would be your third pint... the responding in a relevant language.  The easy answer would be to run them trough Google translate, but that probably would not be ideal.

**Comment by FastLizard4** [comment]
I am against this myself, but the big reason is that we are still the *English* Wikipedia ACC.  We do our checks against the English Wikipedia, enforce the English Wikipedia's Username Policy (and others), etc.  Despite SUL, users who come to us need to understand this.

If we want to broaden our scope to encompass all Wikipedias because of ACC, I think we would need to have a discussion with both the Foundation about the implications of this, as well as internally decide how we want to operate (e.g., whose policies do we enforce, what wikis do we check for sockpuppetry on, etc.).  Internationalization just isn't a bridge we're even close to crossing yet.

**Comment by FastLizard4** [comment]
(Some of the points I mention above aren't issues inherent to ACC either, but to SUL on a whole - for example, the practicability of enforcing enwiki's UPol on accounts now that accounts are global.  As far as I know, there is no global username policy.  But that's a whole other issue that needs a discussion well beyond the scope of ACC.)

**Comment by FastLizard4** [comment]
(Ugh, sorry for the spam :P)

Actually, on second thought, this might be something to consider, but executed in a slightly different way - perhaps we should be offering internationalization insofar as to offer the tool to other language wikis (and other projects, as well) that wish to offer their own ACC.  I think with the way things are, the most practical way to do things would be to have a separate ACC with its own team for each language, since they would be able to specialize in their relevant policies (of course, this would also require a discussion with the Foundation, but anyway).

If this is the case, I think the best way to do internationalization would be to work directly with those interested in running their language's ACC, instead of using Translatewiki or a similar service, simply because ACC is not really of brought enough interest IMO.

**Comment by stwalkerster** [comment]
So looking at it from a technical standpoint, ever since the move to Smarty, it's not been possible to customize interface messages from the web UI - it has to be done in code. I've been pushing this way due to the horrendously fragile and production-dependent nature of how it was implemented.

We could achieve i18n-capability by re-adding this functionality to the web UI, so that other copies of the tool would be able to customise their interface. Maybe that's what we should be looking at.

I do have some minor security concerns for code injection.

For the record, I'm kinda neutral on the technical front for this - it's a nice-to-have but practically we don't need it. As to the bureaucratic management stuff, that's someone else's problem :P

I get the feeling that this probably isn't going to happen, simply because it'll fall pretty damn low on the prioritised list, amongst @FastLizard4 's comments.

**Comment by Technical-13** [comment]
Since I'm no longer an ACC team member even though I am still on the development team, I will try to make this short expecting my input to not mean much to anyone. I agree with @cyberpower678 that this is unnecessary busy work for something that is intended to only serve the English Wikipedia. I'd be afraid that if it was made i18n compatible that the foundation would decide to just take over the project.  I had though that was why some of this kind of stuff had been left out in the first place.

**Comment by stwalkerster** [comment]
Gonna close this for now, if we want to revisit it we can always reopen it :)
