### ISSUE TITLE
No confirmation pop-up for 'COI risk'

### ISSUE THREAD

**Issue by josve05a** [enwikipedia-acc/waca#245]
I didn't get that "confirmation"-pop up when I picked "COI risk", so I never got to see the "Did you do all the steps"-window...which caused me to send an email to #163150 before creating the account (did the wrong order, which I would hav been reminded of, if I got the pop-up. _I think this is what happened_, can't figure out why I would go through with the email, if I got the pop-up stopping me) so..untested...

**Comment by cyberpower678** [comment]
Are you sure it's because there is no pop up message set on the interface?

**Comment by RileyHuntley** [comment]
https://accounts.wmflabs.org/acc.php?action=emailmgmt&edit=12 shows a pop up message set.

**Comment by Matthewrbowker** [comment]
@cyberpower678 I looked, it appears there is one set.

**Comment by cyberpower678** [comment]
I'll shut up then. :p

**Comment by josve05a** [comment]
I can't remmeber 100%, but I can't remember one. My memory might be faulty, but highly suspicious...but...meh

**Comment by stwalkerster** [comment]
Not a clue. 

Can't see anything in the code that'd cause that. Seems to be loading the JS up correctly on production, and there's nothing weird in the JS message that'd point to an escaping issue. Same JS message works on the sandbox, and user has the abortpref set to 0 (correct for the messages)

Incidentally, I discovered that the main create button isn't showing the JS message on the main button, but that's unrelated to this I think

I reckon it's something weird the browser has done because of our crap usage of HTTP GET requests to perform actions - perhaps preload (which is really concerning), or accidental new tab creation, or something? Both of those should get fixed by #232 .

Really weird. At least in this case, no harm done. We probably need a better check than `{if !$currentUser->getAbortPref() && $reason->getJsquestion() != ''}` embedded in the templates though.

**Comment by FastLizard4** [comment]
Fixed by #215.
