### ISSUE TITLE
Suggestion - combine with WikiEduDashboard

### ISSUE THREAD

**Issue by bluerasberry** [enwikipedia-acc/waca#282]
I have no idea what it means to develop tools or connect them to other tools.

I read about this tool, the "Wikipedia Account Creation Interface" for events.

I have regularly organized Wikipedia events since 2010 or earlier. I have some experience, but there are a range of tools available, and I am not broadly aware of the tools which have been developed or which are being developed.

One tool which has been in development since about 2014 and which is still being developed and gaining popularity is the WikiEduDashboard.
https://github.com/WikiEducationFoundation/WikiEduDashboard

This is a tool for event organizers to register all event participants and later generate a report on event outcomes. 

I wish to mention this tool because I think it is the most popular - and perhaps only - tool which event organizers prepare in advance for events. Also, event organizers who use this tool send all event participants to this tool. I anticipate that this tool will become the standard for managing all group Wikimedia events in all languages for all Wikimedia projects, because it already is functional for this purpose and its popularity is increasing.

If the WikiEduDashboard could direct all new users to the "Wikipedia Account Creation Interface", then that would result in a solution to the problem which the dashboard faces in managing events with more than 6 users (the limit on new accounts from a single IP address) and also bring adoption of the WAC Interface as a feature of the dashboard. The same approval process for event organizers using the Dashboard could also be used to approve someone for use of the WAC Interface, which would prevent the need for development of a another social review process.

Perhaps the WAC Interface needs to be independent while it is developed. The workflow in that case would mean that an event organizer could direct people to the WikiEduDashboard for any mix of registered or the first 6 new users, but when the registration cap is hit, then subsequent users would need to request accounts to their event organizer in the WAC Interface then go on to register in the WikiEduDashboard.

**Comment by FastLizard4** [comment]
After reading through this issue, I must admit that I don't know what exactly it is you're proposing.

To confirm, are you aware that this repository is just the backing code for https://accounts.wmflabs.org and is not itself a separate tool intended for end-user use?

**Comment by bluerasberry** [comment]
I had intended to make this comment follow this -
<https://github.com/enwikipedia-acc/waca/issues/281>

No, I am not aware of where I posted this comment and might be lost.

**Comment by FastLizard4** [comment]
@bluerasberry You're in the right place, but I think there's some context missing.

To be specific, what exactly do you mean by "combining" with WikiEduDashboard?  There's various levels of integration possible, from WikiEduDashboard simply including links to ACC (which would involve no work on our part aside from implementing the event management system described in #281) to WikiEduDashboard providing an independent interface to the event management system (which would require us to work with the WikiEduDashboard developers to also design and implement an appropriate [API](https://en.wikipedia.org/wiki/Application_programming_interface) to facilitate communication between ACC and WikiEduDashboard, require the WikiEduDashboard devs to implement an appropriate frontend on their side, and possibly require legal signoffs from the Wikimedia Foundation due to the nature of ACC as handling non-public information).

Perhaps what would be best is if you could describe what you would consider to be the ideal integrated workflow between ACC and WikiEduDashboard, though with the note that I haven't used WikiEduDashboard before, nor do I think anyone else on the ACC dev team has before.  I appreciate that you may be unfamiliar with the process of software development, so I'm happy to work with you on this, but we would need to establish solid technical requirements before we can even consider combining with WikiEduDashboard and what that would entail.

**Comment by dqwiki** [comment]
Closing due to lack of response.
