### ISSUE TITLE
Add an option to create an account without generating a "We created your account" email

### ISSUE THREAD

**Issue by Gestrid** [enwikipedia-acc/waca#445]
This will help in situations where, for one reason or another, an account wasn't created when it was supposed to be.  For example, just today, I custom-closed a request as created (I edited the default email to include some additional links for the user.), but I forgot to click "Create Account" before closing the request.  This meant I had to go in and reset the request, reserve it, and click create account, then create another custom close to apologize to the user for the additional email from us.  If we had a button to allow for closes that didn't generate an email, I could've done all that without alerting the user to the mistake on our end.

**Comment by FastLizard4** [comment]
This is what the "Drop" button does - closes the request without an email.  The procedure in this case is to reset the request, create the account, then leave a comment explaining what happened and drop it.

Since this feature already exists as far as I can tell, I'm closing this issue.  However, if you have something else in mind, please feel free to reopen.

**Comment by stwalkerster** [comment]
@FastLizard4 from a tracking point of view, the system will treat dropped requests as not created - even though it is essentially "change status to closed without notifying the requestor",

This is mostly due to the design of a request only being in a specific queue or "Closed" - the determination of whether the request is closed as created or closed as not created is done by looking at the last log entry with `action like "Closed %"` and comparing it to `emailtemplate` plus a few special cases.

Whether we should track the created/not created status separately to this I think might be the root issue here.
