### ISSUE TITLE
Allow admins to edit requester comments

### ISSUE THREAD

**Issue by JJMC89** [enwikipedia-acc/waca#490]
This would be useful to redact PII instead of needing DB access.

**Comment by stwalkerster** [comment]
I thought I had this covered in another task, but I can't see one.

I've had a plan in the back of my mind for a little while now to move the requester comment out of the `request` table and into the normal `comment` table. By doing this, the existing comment editing code should be able to handle the editing of requester comments without too much difficulty.

I'd also like there to be a way for comments to be flagged for review by normal tool users, and it probably makes sense to tackle both of these at the same time as part of a general overhaul of commenting - see #491

## Rough Action Plan ##
* [ ] Database migration script:
  * Modify `comment.user` to allow null values
  * Add a foreign key on `comment.user` as one doesn't currently appear to exist
  * Add a foreign key on `comment.request` as one doesn't currently appear to exist (though an index does)
  * Migrate `request.comment` to appropriately timestamped rows in `comment`, with `visibility = 'requester'`
  * Drop `request.comment`
* [ ] Modify log display logic to coalesce in the request name instead of the username when the comment has come from the requester
* [ ] Modify comment editing to prevent changing comment visibility when the comment has come from the requester (`user is null`)
* [ ] Modify request creation logic to put the request comment into the `comment` table instead of the `request` table
