### ISSUE TITLE
User statistics EditComment-[cr] is confusing

### ISSUE THREAD

**Issue by DannyS712** [enwikipedia-acc/waca#636]
As far as I can tell, the count of `EditComment-c` and `EditComment-r` entries for a user is the same, with the first referring to log entries where the target is the comment id, and the second referring to the target being the request. Rather than showing both labels on the user statistics view, I suggest only showing one, and using a clearer "Edited a comment" description instead of the internal label

----

As a user,
When I view https://accounts.wmflabs.org/internal.php/statistics/users/detail?user=2059
Expected result:
```
...
Edited a comment | 7
...
```
Actual result:
```
...
EditComment-c | 7
EditComment-r | 7
...
```

**Comment by stwalkerster** [comment]
Yeah, this is one of the side effects of an earlier bad design choice, where log entries can only "affect" one object type, and to avoid a large join between the log and comment tables to filter by request, we decided to duplicate the log entries. This sort of problem (where one log entry is relevant for multiple objects) is becoming more prevalent, and over the years we've chosen to work around it in several different ways - for instance sending reservations - and is actually one of the things that is planned to be fixed in #607 so I'm going to close this in preference to that issue.
