### ISSUE TITLE
Template links should not be relative to wmflabs

### ISSUE THREAD

**Issue by DannyS712** [enwikipedia-acc/waca#638]
Steps to reproduce:
Visit, eg, https://accounts.wmflabs.org/internal.php/welcomeTemplates/view?template=1

Actual result:
Links within the template are relative, and thus don't work
eg `Learn more about editing` is linked to `/wiki/Help:Introduction` which resolves to https://accounts.wmflabs.org/wiki/Help:Introduction

Expected result:
Links within the templates should go to enwiki (i.e. the link should be to https://en.wikipedia.org/wiki/Help:Introduction)

**Comment by stwalkerster** [comment]
At a complete guess, this is probably because the MediaWiki parser on enwiki is handing us relative links. I _think_ the welcome template rendering is basically just the output from the parser, though I'd have to check what's actually going on in that page - it's been too long since I last looked at it.
