### ISSUE TITLE
Usernames can be entirely numbers 

### ISSUE THREAD

**Issue by Ammarpad** [enwikipedia-acc/waca#667]
https://accounts.wmflabs.org/
> Case sensitive, first letter is always capitalized, you do not need to use all uppercase. Note that this need not be your real name. Please make sure you don't leave any trailing spaces or underscores on your requested username. **Usernames may not consist entirely of numbers,** contain the following characters: # / | [ ] { } < > @ % : or exceed 85 characters in length.
  
Emphasis added. I am sure MediaWiki allows numbers-only username, and I know English Wikipedia username policy  does not prohibit such names. So is there a reason for this limitation which does not emanate from the software nor from project policy?

I can understand if this is soft prohibition or there's a rationale for it, but I just want make sure it was not due to mistaken assumption that they're disallowed by the software, (since this is immediately followed with characters truly disallowed for technical reasons).

**Comment by kfiven** [comment]
If somone go to Special:CreateAccount and try to register a number only account, it shows an error i.e "The username "6688743399" is not allowed to prevent confusing or spoofed usernames: Does not contain any letters. Please choose another username." So I doubt MediaWiki allow such creations.

**Comment by dqwiki** [comment]
It could be a global or local titleblacklist filter too. Without knowing the source of it (if someone could look it up), I'm hesitant to offer a change for any of the text.

**Comment by ElHefWiki** [comment]
It does appear to be a technical restriction that accountcreators (at least) can't override. I tried to create a test account with just numbers and failed. The error message given above appears before the creation is submitted, so there's a rule someplace that's looking for this live. Overriding the blacklist returned the same error. Overriding antispoof gives an error "The supplied credentials could not be used for account creation."

I agree that this isn't in any policy that I've seen, but it does seem to be accurate as written.

**Comment by Ammarpad** [comment]
> It does appear to be a technical restriction that accountcreators (at least) can't override. I tried to create a test account with just numbers and failed. 

So how do we have these: https://en.wikipedia.org/wiki/User:72, https://en.wikipedia.org/wiki/User:78?. They're both active editors and have edited in the last few weeks/days.

> The error message given above appears before the creation is submitted, so there's a rule someplace that's looking for this live. Overriding the blacklist returned the same error. Overriding antispoof gives an error "The supplied credentials could not be used for account creation."

There might be a custom  extension doing something here on English/WMF wikis but I didn't make any effort to trace that. I created this issue merely for discussion and out of curiosity.

**Comment by ElHefWiki** [comment]
Sorry, scratch my previous comment. This is an antispoof thing that prevents creating accounts with just numbers, and users with override-antispoof rights (including accountcreators) can do so. I tested it on a couple of accounts just now - one with 2 digits and one with a bunch (11 maybe?) and was able to create both by overriding antispoof. It doesn't appear to be a blacklist thing, since overriding the blacklist had no effect. I'm afraid my technical expertise doesn't get me far enough to chase down where that restriction is implemented or where the error message is coming from.

(My previous failure was because the password cleared out of the form after the first time I submitted the form and I didn't notice, apparently that's the error message you get when trying to create an account with no password when overriding antispoof. Not a particularly helpful message, but I suppose accurate.)

I can think of a variety of reasons why a username with just numbers could be a UPOL violation, but I agree that I'm not aware of a policy that makes this a blanket restriction.

**Comment by stwalkerster** [comment]
Possibly this? https://github.com/wikimedia/mediawiki-extensions-AntiSpoof/blob/master/includes/AntiSpoof.php#L427-L429

**Comment by Ammarpad** [comment]
Thank you all. This issue can be closed now, as there's nothing more to do here. Only-numbers name is not totally disallowed but neither encouraged. If you're requesting account via ACC, then there's no need to choose such usernames. If you create it yourself then that's fine for you.
