### ISSUE TITLE
Routing failing when ACC is in a subfolder

### ISSUE THREAD

**Issue by dqwiki** [enwikipedia-acc/waca#673]
This isn't a bug on the main server because of the domain, but going to https://accounts-dev.wmflabs.org/rc will give you an error vs. https://accounts-dev.wmflabs.org/rc/ which will work

**Comment by stwalkerster** [comment]
I have a strong suspicion this isn't a tool issue, more likely an issue with Apache's underlying routing.

**Comment by stwalkerster** [comment]
Yeah, this is definitely not a problem with the tool itself, it's a problem with our Apache config somewhere.

**Comment by stwalkerster** [comment]
OK, I know what's going on here, and it's a side-effect of several bits of awkward configuration.

accounts-dev runs as a port-based virtual host behind the Labs openstack proxy. As such, Apache thinks it's running on port 8080 (which is correct) but that's not the actual port that it's accessed on publicly.

Apache sees the request for `/rc`, and due to the [DirectorySlash](https://httpd.apache.org/docs/2.4/mod/mod_dir.html#directoryslash) directive, it issues a redirect to `/rc/`, but puts the entire URL in there (as far as apache sees it) instead of making it relative.

Fixes for this include disabling DirectorySlash and acknowledging the security warning; spinning up a new instance just for the dev tools; or possibly switching to name-based vhosts (if that even works behind the labs proxy - which I think it doesn't hence why we're using port-based vhosts).

I'm actually very tempted to "won't fix" this.

**Comment by supertassu** [comment]
> if that even works behind the labs proxy - which I think it doesn't hence why we're using port-based vhosts

It should work just fine, the `Host` header is passed through to the backend server.

**Comment by stwalkerster** [comment]
Will be fixed by enwikipedia-acc/tf@46c38c079f5c1f20d40114ac68d55408b800a359 once the move to bullseye is completed.
