### ISSUE TITLE
Autocreate/autowelcome UI around custom closes needs work

### ISSUE THREAD

**Issue by stwalkerster** [enwikipedia-acc/waca#677]
Custom closes don't currently support auto-creation, but they do support auto-welcome.

The UI for this is unclear that the user must switch to manual creation, create an account, then custom close as created; a scenario which is likely to cause confusion.

We either need to expand custom closes to support autocreate, or make it very clear in the custom close UI that autocreation will not happen.

**Comment by stwalkerster** [comment]
OK, initial plan:
* New actions on "action to take" dropdown:
  * Send email and close request as created. I have already created the account manually.
  * Send email, create the account using my Wikimedia account, and close request as created.
  * Send email, create the account using the bot, and close request as created
* Dump the email body into the job parameters field - it's a blob so should be able to handle it
* Don't set the email template
* Figure out whether we display the parameters in the job information or not
* Change the creation/close request step to look for the custom close email in the job parameters.

**Comment by ElHefWiki** [comment]
No comment as to the implementation, but assuming you make Custom create work with autocreate, I think this is usable. Questions from my end:

- Can/will my available options adjust based on what actions I have access to and/or have enabled in prefs? Ideally, the options in Custom should mirror whatever options were available to me on the preceding request.
- If manual create is selected, does Custom check that the account has actually been created like regular Created! does? I seem to remember that it doesn't now - it should, especially since we're adding another level of complexity to this. (Please disregard if I'm wrong - this one's from memory and I haven't tested it.)
- If autocreate fails, where does the email text land so I can reuse it and not have to rewrite it?

**Comment by stwalkerster** [comment]
* Yes, options will hide themselves based on whether you have access to that or not and whether or not the option is actually usable. In other words, you'll only see the "create via oauth" option if 1) you're allowed to use OAuth creation by the roles you currently hold, and 2) your current OAuth grants permit you to use it. This is _slightly_ different to the main view request page, where if you are allowed to use an option it will be visible, but if your oauth grants don't permit you to use it, you'll see an error directing you to fix your OAuth config. (Feel free to try it by going to https://en.wikipedia.org/wiki/Special:OAuthManageMyGrants , clicking "manage access", and remove the create account grant, followed by logging in/out of the tool or clicking the refresh button at the bottom of your tool prefs)
* Good question.
* Also a good question. I _think_ it'll appear on the jobqueue entry, but I don't think it'll appear anywhere else.

**Comment by ElHefWiki** [comment]
Will the job write the email text to the request log when it closes the request then?

**Comment by stwalkerster** [comment]
When it actually closes the request, yes, it will.

**Comment by stwalkerster** [comment]
So from some poking around at the code, it looks like manual custom closes will not check the account is actually created, no. I'd say that should probably be part of a separate issue, and isn't something I think I'm going to fix as part of this.
