### ISSUE TITLE
Title blacklist configuration partially implemented

### ISSUE THREAD

**Issue by ElHefWiki** [enwikipedia-acc/waca#730]
If the interface detects that a request is blacklisted, it should automatically get sorted into the flagged users queue, as antispoof hits are. Presently it seems they are left in the main queue. Example: 316634

**Comment by stwalkerster** [comment]
Curious; this should already happen.

**Comment by stwalkerster** [comment]
OK, so it turns out this wasn't turned on. :facepalm: 

However, it also looks like the configuration flag for this is only turning it off in one place (`RequestValidationHelper`), but not on `PageViewRequest`. It also looks like PageViewRequest uses a helper class, whereas RequestValidationHelper doesn't.

I'm going to repurpose this issue to clean up the code so it's not as messy.

**Comment by methecooldude** [comment]
This is working correctly and can be closed
