### ISSUE TITLE
Custom create message is lost if request is hospitaled

### ISSUE THREAD

**Issue by ElHefWiki** [enwikipedia-acc/waca#731]
See request 316347 - I wrote a custom message and submitted the request to autocreate. The request hit antispoof and was sent to hospital. It was previously indicated in issue #677 that the email text would write to the job queue following the job failure, but that didn't happen. Not a big deal in this case since I was just copy/pasting from two existing messages, but re-wordsmithing something more complex would be no fun. That text should show up somewhere so it can be reused.

I suppose my ideal solution would be filling it back in if the ACCer sends another custom message to the request (or at least giving the option to do so), but writing it into the log or queue or something would be fine.

**Comment by stwalkerster** [comment]
I see request #316347 has three jobs associated with it:
* job 6138 (create via OAuth), failed due to antispoof hit
* job 6139 (welcome user), cancelled due to 6138's failure
* job 6140 (welcome user), completed successfully

If I go into the details for the failed job 6138 ( https://accounts.wmflabs.org/internal.php/jobQueue/view?id=6138 ), I can see the email body listed. Sure, it's a bit hidden, but it does appear to be present.

**Comment by ElHefWiki** [comment]
Ha, I've never had to click that far into the job queue before. I didn't even know that screen was there, but it is there, so resolving.
