### ISSUE TITLE
Create an IRC ping for flagged comments

### ISSUE THREAD

**Issue by dqwiki** [enwikipedia-acc/waca#777]
Helpmebot would simply send:

!accadmin requested for a flagged comment ([comment number])

**Comment by stwalkerster** [comment]
OK, a few questions from me:
* Is this actually needed? Flagged comments are already put in a queue with a flag to attract admin attention whenever an admin logs into the tool. I'll pull together some stats from the database to show our response time on this
* Is this going to encourage admins to purge the comment of private data while that data is still useful? There's been a number of times when I've seen a request kicked to the CU queue where the data in the comment has already been removed, but where that information would have been very useful (especially IPv6 addresses etc), and I'm more inclined to hide comments on open requests from the flagged queue by default
* When would you want this ping to be sent to the channel? On flagging of the comment? On request closure?

**Comment by dqwiki** [comment]
There is maybe 2 solutions to this.
1) Hiding the data once its flagged
2) Ping & bubble notification only after the request is closed
This better handles private data and then gets the removal done as soon as possible.
The other thing the ping would do, which is a side benefit, would get me back more active with the tool ;)
As far as it actually being needed, I obviously don't have the stats, but if we wait until the request is closed like noted above, I'd like us to get to data removal ASAP so the request can be viewed again if it comes up as part of another request.

**Comment by stwalkerster** [comment]
```sql
WITH flag AS (
    SELECT flagLog.objectid, min(flagLog.timestamp) ts
    FROM log flagLog
    WHERE flagLog.objecttype = 'Comment' and flagLog.action in ('FlaggedComment')
    GROUP BY flagLog.objectid
),
unflag AS (
    SELECT unflagLog.objectid, max(unflagLog.timestamp) ts
    FROM log unflagLog
    WHERE unflagLog.objecttype = 'Comment' and unflagLog.action in ('UnflaggedComment')
    GROUP BY unflagLog.objectid
)
SELECT flag.objectid comment, flag.ts flag_time, unflag.ts unflag_time, timestampdiff(HOUR, flag.ts, unflag.ts) as delta_hours FROM flag
INNER JOIN unflag ON flag.objectid = unflag.objectid
ORDER BY flag.objectid ASC;
```

That query produces the relevant stats 😁 There are some comments (four) which were unflagged and re-flagged - this assumes the worst case (min flag time vs max unflag time) for each comment.

Looks like we've _mostly_ caught comments within a few hours of them being flagged recently, though if you go back before July it's mostly caught within a few days.

**Comment by stwalkerster** [comment]
So, initial plan of action (:+1: or :-1:?):
1. Hide flagged comments for open requests from the ./flaggedComments queue
2. Hide flagged comments from ./viewRequest unless the user meets the existing "see private data" criteria (admin/checkuser or has reserved the request), but leaving a placeholder in place so users know there's something they can't see and can ask/reserve if they need it

If we agree on the above, I'm happy to spec out the changes (probably in other tasks so this one can stay focussed on the IRC ping or not.

----

I'm happy to add an IRC ping too, I just wonder if it's worth doing it during the midnight private data cleanup batch rather than on request close. That way, there's one ping per day to remind admins to clean up anything that needs cleaned up?

**Comment by dqwiki** [comment]
One ping a day is fine with me also.

**Comment by stwalkerster** [comment]
OK, these first two bits are easy, so I'm happy if someone else wants to pick them up.

Part 1 is probably a simple case of changing [`Comment::getFlaggedComents(...)`](https://github.com/enwikipedia-acc/waca/blob/9a1ce7c91e6bb953f90f89604055d239b807665f/includes/DataObjects/Comment.php#L76) to filter on whether the request is open or not. A simple SQL JOIN is likely all that's needed.

Part 3 (the daily IRC ping) can be done in [`Waca\ConsoleTasks\ClearOldDataTask`](https://github.com/enwikipedia-acc/waca/blob/9a1ce7c91e6bb953f90f89604055d239b807665f/includes/ConsoleTasks/ClearOldDataTask.php). A call to `Comment::getFlaggedComments(...)` and a call to a new method in [`Waca\Helpers\IrcNotificationHelper`](https://github.com/enwikipedia-acc/waca/blob/9a1ce7c91e6bb953f90f89604055d239b807665f/includes/Helpers/IrcNotificationHelper.php) - I'd recommend wording like "X flagged comments awaiting cleanup" rather than @dqwiki's wording above given the change to one-per-day.

**Comment by stwalkerster** [comment]
Part 2... part 2...

PageViewRequest's `main()` function has a variable defined called `$allowedPrivateData`. This *should* be a boolean flag for whether to show the interesting bits or not. I'd recommend passing this into `setupLogData(...)`

https://github.com/enwikipedia-acc/waca/blob/cf679d0eb7c5491580df9b8f931c4d063760f38b/includes/Pages/PageViewRequest.php#L93-L97

There's an interesting block of code here to populate the table:

https://github.com/enwikipedia-acc/waca/blob/cf679d0eb7c5491580df9b8f931c4d063760f38b/includes/Pages/PageViewRequest.php#L219-L235

... and the table is defined here:

https://github.com/enwikipedia-acc/waca/blob/cf679d0eb7c5491580df9b8f931c4d063760f38b/templates/view-request/request-log.tpl#L73

My thinking (which may or may not work) would be to not set the comment entry in the array if the comment is both flagged and the user can't see private data, but instead set a new 'hidden' field. That way we can have a placeholder for the hidden comment in the template, without needing too much logic in the template itself
