### ISSUE TITLE
"Skip automatic welcome on account creation" does not work

### ISSUE THREAD

**Issue by mdaniels5757** [enwikipedia-acc/waca#877]
To reproduce: Manually create an account on ruwiki in the ruwiki queue. Select "Skip automatic welcome on account creation", then close as "Created!".
Observe that a welcome user job is launched. This should not happen (see below).

https://github.com/enwikipedia-acc/waca/blob/5f75b59c628b392c8320d66e7b61d5ba4ae95b27/includes/Pages/RequestAction/PageCloseRequest.php#L265-L269

Example request/job ids: 337604/15628.

\* Note: it's possible that this toggle doesn't work for automatic creation, in other queues, or after manual creation on enwiki. But I haven't tried any of those, as I want welcoming in every scenario except this one (where the job will fail because there is no corresponding enwiki user).

**Comment by stwalkerster** [comment]
I've spotted this locally too; I thought I'd raised a ticket for it already but I can't find it.

I think this flag works, but only when the request creation doesn't hit a confirmation message. Does that tally with your observations too?

**Comment by mdaniels5757** [comment]
That sounds plausible. Looking at https://github.com/enwikipedia-acc/waca/blob/5f75b59c628b392c8320d66e7b61d5ba4ae95b27/includes/Pages/RequestAction/PageCloseRequest.php#L59-L61
and https://github.com/enwikipedia-acc/waca/blob/5f75b59c628b392c8320d66e7b61d5ba4ae95b27/includes/Pages/RequestAction/PageCloseRequest.php#L156-L165, it looks processWelcome will never run if the confirmation message shows?

**Comment by stwalkerster** [comment]
Without looking into it much at all, I suspect that it may be because of how the confirm messages work.

Those messages are triggered as the result of a form POST from the view request page, and clicking the "yes, carry on anyway" button essentially re-POSTs the same form (constructed invisibly with input type=hidden elements) with an additional flag set saying "yes I'm sure about the flobadob check".

My suspicion is that the skip welcome (and maybe the creation method? Probably should check) aren't being passed through by the confirm page, and thus it's defaulting to skip=false.

Again, I've not looked at this in any detail, so I could be wildly wrong. Some debugging to confirm or reject my thoughts might be needed

**Comment by stwalkerster** [comment]
> https://github.com/enwikipedia-acc/waca/blob/5f75b59c628b392c8320d66e7b61d5ba4ae95b27/includes/Pages/RequestAction/PageCloseRequest.php#L156-L165
> it looks processWelcome will never run if the confirmation message shows? But if that's right I'm not sure how the job gets enqueued?

So having read this properly on a non-mobile client, you're correct. If a confirmation message shows, the entire web request flow stops and the request isn't created/closed, welcome jobs aren't enqueued, etc. This is *because* the confirmation message becomes the end result of the web request, and clicking the "yes, continue" button triggers a new web request.

----

Looking more closely at the code, I think my original suspicion is correct.

This hunk of code will call into the confirmation:
https://github.com/enwikipedia-acc/waca/blob/5f75b59c628b392c8320d66e7b61d5ba4ae95b27/includes/Pages/RequestAction/PageCloseRequest.php#L59-L61

Which does the creation check, and if it fails shows the confirmation message:

https://github.com/enwikipedia-acc/waca/blob/5f75b59c628b392c8320d66e7b61d5ba4ae95b27/includes/Pages/RequestAction/PageCloseRequest.php#L156-L165

That confirmation message is configured with some data about the action that was attempted (namely the request and the close template used - custom closes are handled separately)

https://github.com/enwikipedia-acc/waca/blob/5f75b59c628b392c8320d66e7b61d5ba4ae95b27/includes/Pages/RequestAction/PageCloseRequest.php#L222-L238

The relevant template uses those values to populate hidden form fields:
https://github.com/enwikipedia-acc/waca/blob/5f75b59c628b392c8320d66e7b61d5ba4ae95b27/templates/close-confirmations/account-created.tpl#L21-L27


As you found in this block, skipping the welcome depends on a bool field called `skipAutoWelcome` to be posted with the web request:
https://github.com/enwikipedia-acc/waca/blob/5f75b59c628b392c8320d66e7b61d5ba4ae95b27/includes/Pages/RequestAction/PageCloseRequest.php#L265-L269

That variable is never actually set in that template though, so it's value is lost and defaults to `false`:
https://github.com/enwikipedia-acc/waca/blob/5f75b59c628b392c8320d66e7b61d5ba4ae95b27/includes/WebRequest.php#L235-L240

----

The fix, as you can guess, will be fairly simple - dump the value of `skipAutoWelcome` into a new hidden field on the confirmation message. However, it's possible for this to be stopped several times as there are several confirmations. We'll need to make sure this fix is applied for all three.
